import os
import shutil
import subprocess

def check_path_exists(path) -> bool:
    return os.path.exists(path=path)

def check_is_file(file) -> bool:
    return os.path.isfile(file)

def check_is_dir(dir_path) -> bool:
    return os.path.isdir(dir_path)

def is_empty_file(file):
    return not (check_is_file(file) and os.path.getsize(file) > 0)

def do_not_edit_tips():
    return f"/*This file is generated by Molingo, DO NOT edit it manually. */\n"

def get_command_path(name):
    return shutil.which(name)

def install_with_brew(name):
    path = get_command_path("brew")
    run([path, "install", name])
        
def run(command):
    try:
        result = subprocess.run(command, capture_output=True, text=True)
        print(result.stdout)
    except Exception as e:
        print(f"An error occurred while running the brew command: {e}")