import os

def chech_path_exists(path) -> bool:
    return os.path.exists(path=path)

def check_is_file(file) -> bool:
    return os.path.isfile(file)

def check_is_dir(dir_path) -> bool:
    return os.path.isdir(dir_path)

def is_empty_file(file):
    return not (check_is_file(file) and os.path.getsize(file) > 0)

def do_not_edit_tips():
    return f"/*This file is generated by Molingo, DO NOT edit it manually. */\n"